-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 19:33:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CADASTRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CADASTRO` (
  `placa` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `observacoes` VARCHAR(1000) NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `telefone` INT NOT NULL,
  `ddd` INT NULL,
  PRIMARY KEY (`telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `rg` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone_telefone` INT NOT NULL,
  PRIMARY KEY (`rg`, `telefone_telefone`),
  INDEX `fk_CLIENTE_telefone1_idx` (`telefone_telefone` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_telefone1`
    FOREIGN KEY (`telefone_telefone`)
    REFERENCES `mydb`.`telefone` (`telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `CLIENTE_rg` INT NOT NULL,
  PRIMARY KEY (`idendereco`, `CLIENTE_rg`),
  INDEX `fk_endereco_CLIENTE_idx` (`CLIENTE_rg` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_CLIENTE`
    FOREIGN KEY (`CLIENTE_rg`)
    REFERENCES `mydb`.`CLIENTE` (`rg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orcamento` (
  `CLIENTE_rg` INT NOT NULL,
  `CLIENTE_telefone` INT NOT NULL,
  `CADASTRO_placa` VARCHAR(45) NOT NULL,
  `orcamento` DOUBLE NOT NULL,
  `pecas` VARCHAR(1000) NULL,
  PRIMARY KEY (`CLIENTE_rg`, `CLIENTE_telefone`, `CADASTRO_placa`),
  INDEX `fk_CLIENTE_has_CADASTRO_CADASTRO1_idx` (`CADASTRO_placa` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_CADASTRO_CLIENTE1_idx` (`CLIENTE_rg` ASC, `CLIENTE_telefone` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_CADASTRO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_rg` , `CLIENTE_telefone`)
    REFERENCES `mydb`.`CLIENTE` (`rg` , `telefone_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_CADASTRO_CADASTRO1`
    FOREIGN KEY (`CADASTRO_placa`)
    REFERENCES `mydb`.`CADASTRO` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanico` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reparo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reparo` (
  `idreparo` INT NOT NULL,
  `tempo` DATETIME NULL,
  `elevador` INT NULL,
  `orcamento_CLIENTE_rg` INT NOT NULL,
  `orcamento_CLIENTE_telefone` INT NOT NULL,
  `orcamento_CADASTRO_placa` VARCHAR(45) NOT NULL,
  `mecanico_cpf` INT NOT NULL,
  PRIMARY KEY (`idreparo`, `orcamento_CLIENTE_rg`, `orcamento_CLIENTE_telefone`, `orcamento_CADASTRO_placa`, `mecanico_cpf`),
  INDEX `fk_reparo_orcamento1_idx` (`orcamento_CLIENTE_rg` ASC, `orcamento_CLIENTE_telefone` ASC, `orcamento_CADASTRO_placa` ASC) VISIBLE,
  INDEX `fk_reparo_mecanico1_idx` (`mecanico_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_reparo_orcamento1`
    FOREIGN KEY (`orcamento_CLIENTE_rg` , `orcamento_CLIENTE_telefone` , `orcamento_CADASTRO_placa`)
    REFERENCES `mydb`.`orcamento` (`CLIENTE_rg` , `CLIENTE_telefone` , `CADASTRO_placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_mecanico1`
    FOREIGN KEY (`mecanico_cpf`)
    REFERENCES `mydb`.`mecanico` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
