# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\GABRIEL_LUZ\Documents\BD I\avabd\pesquisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 303)
        MainWindow.setStyleSheet("background-color: rgb(19, 55, 59);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(12, 12, 12);")
        self.label_2.setObjectName("label_2")
        self.v_lista = QtWidgets.QTableWidget(self.centralwidget)
        self.v_lista.setGeometry(QtCore.QRect(30, 80, 881, 111))
        self.v_lista.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.v_lista.setShowGrid(True)
        self.v_lista.setGridStyle(QtCore.Qt.NoPen)
        self.v_lista.setObjectName("v_lista")
        self.v_lista.setColumnCount(5)
        self.v_lista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.v_lista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.v_lista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.v_lista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.v_lista.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.v_lista.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RESULTADO PESQUISA"))
        item = self.v_lista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PLACA"))
        item = self.v_lista.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MODELO"))
        item = self.v_lista.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CATEGORIA"))
        item = self.v_lista.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "OBSERVAÇÕES"))
        item = self.v_lista.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ENTRADA"))
